In [1]:
import tensorflow as tf
import tensorflow.keras.layers as layers

In [3]:
# 我们可以使用SimpleRNN方便计算
layer=layers.SimpleRNN(64)
x = tf.random.normal([4,80,100])
out = layer(x)
out.shape

TensorShape([4, 64])

In [5]:
# 如果希望返回所有时间戳上的输出列表，可以设置return_sequences=True
layer=layers.SimpleRNN(64, return_sequences=True)
out = layer(x)
out

<tf.Tensor: shape=(4, 80, 64), dtype=float32, numpy=
array([[[-0.6438159 ,  0.92671704, -0.35837406, ...,  0.84868   ,
         -0.05426907, -0.8058341 ],
        [-0.9098431 , -0.84464353, -0.9803921 , ..., -0.05080878,
         -0.9451581 , -0.41283393],
        [ 0.90869296, -0.9136027 ,  0.45295522, ...,  0.4855264 ,
         -0.1060161 , -0.8761614 ],
        ...,
        [ 0.5210651 ,  0.12006729, -0.53821176, ..., -0.9728854 ,
          0.67310387,  0.69885284],
        [ 0.38986725,  0.84887   , -0.05098079, ..., -0.05012174,
         -0.42323372, -0.91710997],
        [ 0.82634604,  0.20477104,  0.8888786 , ...,  0.9370532 ,
         -0.05765812, -0.672405  ]],

       [[ 0.2809511 ,  0.91723675, -0.72741693, ...,  0.03337909,
          0.08961242,  0.8950285 ],
        [-0.5166496 , -0.71095455,  0.9972403 , ..., -0.8326687 ,
         -0.57530236, -0.3236516 ],
        [ 0.4355584 ,  0.05937548,  0.6786724 , ...,  0.89762145,
         -0.65085506,  0.928676  ],
        ...,
 

In [6]:
# 我们可以堆叠多个SimpleRNN
net= tf.keras.Sequential([
    layers.SimpleRNN(64,return_sequences=True),
    layers.SimpleRNN(64),
])
out=net(x)

In [7]:
out

<tf.Tensor: shape=(4, 64), dtype=float32, numpy=
array([[ 0.2606573 , -0.29040012, -0.72204435, -0.05749176, -0.6096765 ,
         0.22143808,  0.6089341 , -0.6838607 ,  0.8288612 , -0.7187431 ,
        -0.799866  ,  0.436478  , -0.16572757,  0.6015371 ,  0.11696944,
        -0.67529374, -0.8317128 , -0.53131586, -0.56273633,  0.9725455 ,
        -0.57028055, -0.7121625 , -0.3087142 , -0.94853556, -0.89084744,
         0.05356846,  0.8646842 , -0.19901262, -0.5592915 , -0.768492  ,
         0.08132476, -0.51686907, -0.10468075,  0.0898843 , -0.7001862 ,
         0.21294037, -0.6237851 , -0.430837  ,  0.16828825, -0.82994145,
        -0.1936945 ,  0.34185869, -0.60818046, -0.6334631 , -0.6309652 ,
        -0.87506557, -0.8090926 , -0.07714748, -0.39162207, -0.09111828,
         0.3262649 ,  0.27518153, -0.65817964, -0.00570237, -0.9183995 ,
        -0.83695316,  0.5998377 ,  0.82429713,  0.7721742 , -0.4218654 ,
        -0.73547745,  0.7377933 ,  0.42237252,  0.9600058 ],
       [ 0.186