In [1]:
import tensorflow as tf

# Gradient Clipping

### （1）方法1：直接对张量进行限幅

In [2]:
a=tf.random.uniform([2,2])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.9462669 , 0.25288463],
       [0.04284561, 0.34460914]], dtype=float32)>

In [4]:
b = tf.clip_by_value(a,0.4,0.6)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.6, 0.4],
       [0.4, 0.4]], dtype=float32)>

### （2）方法2：通过对限制梯度张量W的范数来实现梯度裁剪

In [10]:
a=tf.random.uniform([2,2]) * 5
# 按范数方式裁剪
b = tf.clip_by_norm(a, 5)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.5499158 , 2.8768535 ],
       [3.8180952 , 0.54037213]], dtype=float32)>

In [11]:
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.3415132 , 2.6417305 ],
       [3.5060456 , 0.49620795]], dtype=float32)>

# Gradient Scaling